from __future__ import annotations

from pathlib import Path
from typing import Protocol

from plugins.labeling.domain.core.models import (
    AnnotationSet,
    ArtifactRef,
    Dataset,
    ImageAsset,
    LabelSchema,
    ReviewDecision,
    SystemTenant,
    TenantUserMapping,
    AnnotationTask,
)


class MetadataStore(Protocol):
    """新工業標注平台的 Metadata Store Protocol（三張表）。"""

    # --- SystemTenant ---
    def save_tenant(self, tenant: SystemTenant) -> SystemTenant: ...
    def get_tenant(self, tenant_id: str) -> SystemTenant | None: ...
    def list_tenants(self) -> list[SystemTenant]: ...
    def delete_tenant(self, tenant_id: str) -> None: ...

    # --- TenantUserMapping ---
    def add_user_mapping(self, mapping: TenantUserMapping) -> TenantUserMapping: ...
    def list_user_mappings(self, tenant_id: str, ant_id: str | None = None) -> list[TenantUserMapping]: ...
    def list_all_user_mappings(self, tenant_id: str) -> list[TenantUserMapping]: ...
    def remove_user_mapping(self, tenant_id: str, user_id: str, ant_id: str | None = None) -> None: ...
    def is_user_authorized(self, tenant_id: str, user_id: str) -> bool: ...

    # --- AnnotationTask ---
    def save_task(self, task: AnnotationTask) -> AnnotationTask: ...
    def get_task(self, task_id: str) -> AnnotationTask | None: ...
    def list_tasks(self, tenant_id: str, ant_active: int | None = None) -> list[AnnotationTask]: ...
    def get_task_by_ant_id(self, tenant_id: str, ant_id: str) -> AnnotationTask | None: ...

    # --- 保留舊 dataset/schema/annotation_set 介面，供 FormatRegistry 測試用 ---
    def save_dataset(self, dataset: Dataset) -> Dataset: ...
    def get_dataset(self, dataset_id: str) -> Dataset | None: ...
    def list_datasets(self) -> list[Dataset]: ...
    def save_asset(self, asset: ImageAsset) -> ImageAsset: ...
    def find_asset_by_checksum(self, dataset_id: str, checksum: str) -> ImageAsset | None: ...
    def list_assets(self, dataset_id: str) -> list[ImageAsset]: ...
    def save_schema(self, schema: LabelSchema) -> LabelSchema: ...
    def get_schema(self, schema_id: str) -> LabelSchema | None: ...
    def save_annotation_set(self, annotation_set: AnnotationSet) -> AnnotationSet: ...
    def get_annotation_set(self, annotation_set_id: str) -> AnnotationSet | None: ...
    def list_annotation_sets(self, dataset_id: str | None = None) -> list[AnnotationSet]: ...
    def save_review_decision(self, decision: ReviewDecision) -> ReviewDecision: ...
    def save_export(self, export_id: str, annotation_set_id: str, payload: dict) -> dict: ...
    def get_export(self, export_id: str) -> dict | None: ...


class ArtifactStore(Protocol):
    def put_file(
        self,
        source_path: Path | str,
        relative_dir: str,
        media_type: str,
        artifact_id: str | None = None,
        copy: bool = True,
    ) -> ArtifactRef: ...

    def write_bytes(
        self,
        relative_path: str,
        data: bytes,
        media_type: str,
        artifact_id: str | None = None,
    ) -> ArtifactRef: ...
